### ISSUE TITLE
编译失败：stmobile-lib

### ISSUE THREAD

**Issue by DerekYanJ** [AgoraIO/Agora-With-SenseTime#10]
/Users/derekyan/Downloads/Agora-With-SenseTime-master/Agora-Video-With-SenseTime-Android/sensetime/CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
stmobile-lib
    linked by target "stmobile_jni" in directory /Users/derekyan/Downloads/Agora-With-SenseTime-master/Agora-Video-With-SenseTime-Android/sensetime
/Users/derekyan/Downloads/Agora-With-SenseTime-master/Agora-Video-With-SenseTime-Android/sensetime/CMakeLists.txt : C/C++ debug|arm64-v8a : Configuration failed.
executing external native build for cmake /Users/derekyan/Downloads/Agora-With-SenseTime-master/Agora-Video-With-SenseTime-Android/sensetime/CMakeLists.txt

**Comment by DerekYanJ** [comment]
缺少/src/main/jni/prebuilt/lib/下得文件 有没有商汤得联系方式

**Comment by wenjiefeng79318** [comment]
同问，也是遇到这样的错误，是少stmobile-lib吗
