### ISSUE TITLE
4.0.0-rc分支，安卓商汤美颜，不支持采集分辨率更新。

### ISSUE THREAD

**Issue by mediaios** [AgoraIO/Agora-With-SenseTime#18]
4.0.0-rc分支，安卓商汤美颜，不支持采集分辨率更新。

如果采集分辨率不固定为720P，用户设置的videoEncoderConfiguration更新的情况下，画面会发生裁剪变形。 

根因：onCapture中的商汤美颜模块，不支持采集分辨率更新。 

望修复。

**Comment by xgfd3** [comment]
已修复：https://github.com/AgoraIO/Agora-With-SenseTime/commit/ebe5afbad8b5ff5a69d2170f7ef07cb550a85e22
